steps:
- name: gcr.io/cloud-builders/git
  args:
  args: [
    'clone',
    'https://github.com/online-ventures/$REPO_NAME.git'
    ]
- name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '-f', 'deploy/Dockerfile',
    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '.'
    ]
  timeout: 600s
- name: gcr.io/cloud-builders/docker
  args: [
    'push',
    'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
    ]
images: [
  'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
  ]
