steps:
# Get the previous docker build.  Allows using it as a cache-from
- name: gcr.io/cloud-builders/docker
  args:
  - pull
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'

# Get the repo.  Make sure to clone the contents directly
- name: gcr.io/cloud-builders/git
  args:
  - clone
  - 'https://github.com/online-ventures/$REPO_NAME.git'

# Build the new docker image
- name: gcr.io/cloud-builders/docker
  dir: $REPO_NAME
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
    '-f', 'docker/app/Dockerfile',
    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '.']
  timeout: 600s

# Push it to gcr.io as latest
- name: gcr.io/cloud-builders/docker
  args:
  - push
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'

# Save this build as well according to commit sha
images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
