steps:
- name: gcr.io/cloud-builders/git
  args:
  args: [
    'clone',
    'https://github.com/online-ventures/lighthouselens.git'
    ]
- name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '-f', 'deploy/Dockerfile',
    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '.'
    ]
  timeout: 600s
- name: gcr.io/cloud-builders/docker
  args: [
    'push',
    'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
    ]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - delete
    - pods
    - -l
    - app=lighthouselens
    - --namespace=default
images: [
  'gcr.io/$PROJECT_ID/$REPO_NAME'
  ]
