version: "3.7"
volumes:
  postgres-data:
    name: lhl-postgres-data
  redis-data:
    name: lhl-redis-data
  bundle-cache:
    name: lhl-bundle-cache
services:
  app:
    build:
      context: ./docker/dev
      dockerfile: Dockerfile
    image: lighthouselens/rails
    command: rails server -b 0.0.0.0
    environment:
      APP_NAME: mce
      NODE_ENV: ${NODE_ENV:-development}
      RAILS_ENV: ${RAILS_ENV:-development}
      YARN_CACHE_FOLDER: /app/node_modules/.yarn-cache
      BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
      HISTFILE: /app/log/.bash_history
      PSQL_HISTFILE: /app/log/.psql_history
      EDITOR: vim
      CONTACT_RECIPIENT: mail@gronows.com
      REDIS_URL: redis://redis:6379/0
    ports:
      - "3200:3000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - bundle-cache:/usr/local/bundle
    stdin_open: true
    tty: true
  db:
    environment:
      POSTGRES_PASSWORD: password
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5482:5432"
  redis:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - "6380:6379"
