version: '3.2'
volumes:
  postgres-data:
  redis-data:
  bundle-cache:
services:
  rails:
    image: lighthouselens/rails
    environment:
    - RAILS_ENV=development
    - EDITOR=vim
    - THOR_MERGE=vim
    - CONTACT_RECIPIENT=mail@gronows.com
    ports:
    - "3200:3000"
    depends_on:
    - db
    - redis
    - sidekiq
    volumes:
    - .:/app
    - bundle-cache:/bundle
    stdin_open: true
    tty: true
  sidekiq:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    image: lighthouselens/rails
    command: bundle exec sidekiq
    environment:
      - RAILS_ENV=development
      - EDITOR=vim
      - CONTACT_RECIPIENT=mail@gronows.com
    ports:
      - "3201:3000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - bundle-cache:/bundle
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5482:5432"
  redis:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - "6380:6379"
